### ISSUE TITLE
Forbidden Access - Your GitHub account does not have a public email address

### ISSUE THREAD

**Issue by piec** [TrustInSoft/TrustInSoft#1]
Hi,

When trying to sign-in with github to the TrustInSoft Analyzer I'm getting the following error:

---

![image](https://user-images.githubusercontent.com/781471/32316071-f823eeb6-bfae-11e7-86f7-c6188203e8af.png)

---

My github account seems to have a public email though:
![image](https://user-images.githubusercontent.com/781471/32316033-cebe319e-bfae-11e7-9afa-38d2dced5600.png)

Thanks

**Comment by Aaylor** [comment]
Hi,

TrustInSoft Analyzer actually relies on the **visible** email address of the user. It avoids requiring access to every email addresses registered by the user (even the non-public one). We will change the word __public__ to __visible__ to avoid confusion.

In the future, we will also provide a way for user to log-in to TrustInSoft Analyzer by giving access to the list of email address.

Thanks for your feedback,
Loïc Runarvot - TrustInSoft

**Comment by piec** [comment]
Ok thanks
