### ISSUE TITLE
  Can TSnippet detect strict aliasing violations?

### ISSUE THREAD

**Issue by aprell** [TrustInSoft/TrustInSoft#8]
More a question than an issue: Can [TSnippet](https://taas.trust-in-soft.com/tsnippet/) detect undefined behavior resulting from strict aliasing violations? If I'm not mistaken, I remember reading that TIS Kernel performs, or can perform, some sort of alias analysis.

Either way, thank you for making such a useful tool available!

**Comment by Aaylor** [comment]
Hello aprell,

You are right, **TIS Kernel** supports a beta version of strict aliasing violiations analysis, but it is not available yet in **TSnippet**. It will be implemented in a future release.

Thanks for your feedback,
Loïc Runarvot,
TrustInSoft

**Comment by aprell** [comment]
Good to know, thank you. Looking forward to future releases!
